version: '3.8'

services:

  # Ollama service for local LLM models
  # Using remote Ollama at 192.168.100.25:11434; local service disabled

  # FastAPI Backend
  backend:
    build:
      context: ./smtapp_core
      dockerfile: Dockerfile
    container_name: smtapp_backend
    environment:
      - DATABASE_URL=sqlite:////app/smtapp.db
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - ./smtapp_core:/app
      - uploads_data:/app/uploads
    depends_on:
      ollama:
        condition: service_started
    networks:
      - smtapp_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./smtapp_client
      dockerfile: Dockerfile
    container_name: smtapp_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./smtapp_client:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - smtapp_network

volumes:
  ollama_data:
  uploads_data:

networks:
  smtapp_network:
    driver: bridge

